# genk8s:hash=ee7cc7112b8b67bcd2de21bb77c7f6f5
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/cert-manager/stage/rendered/
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/argocd/stage/rendered/
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/cnpg/resources/
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  syncPolicy:
    # CNPG requires this
    # https://github.com/cloudnative-pg/charts/issues/325
    syncOptions:
    - ServerSideApply=true
    automated:
      enabled: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gateway
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: kubernetes/gateway/resources/
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  - path: kubernetes/gateway/stage/
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gateway
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: kubernetes/external-secrets/stage/
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
