apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/cert-manager/stage/rendered
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/argocd/stage/rendered
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cnpg
  namespace: argocd
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/cnpg/resources/
    repoURL: https://github.com/gpo/gpo-platform-configs
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: gateway
  namespace: argocd
spec:
  destination:
    namespace: gateway
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: kubernetes/gateway/resources/
      repoURL: https://github.com/gpo/gpo-platform-configs
      targetRevision: HEAD
    - path: kubernetes/gateway/stage
      repoURL: https://github.com/gpo/gpo-platform-configs
      targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: kubernetes/external-secrets/stage/rendered
      repoURL: https://github.com/gpo/gpo-platform-configs
      targetRevision: HEAD
    - path: kubernetes/external-secrets/stage
      repoURL: https://github.com/gpo/gpo-platform-configs
      targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: superset
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: kubernetes/superset/stage/rendered
      repoURL: https://github.com/gpo/gpo-platform-configs
      targetRevision: HEAD
    - path: kubernetes/superset/stage
      repoURL: https://github.com/gpo/gpo-platform-configs
      targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
