# genk8s:hash=9cc2f9dc819b21f1de9adb0967b79ce9
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: superset
  namespace: superset
  labels:
    gateway: gpotools
spec:
  # this connects us to the gateway
  parentRefs:
  - kind: Gateway
    name: gpotools
    namespace: gateway
    sectionName: tls
  hostnames:
  - "superset.gpotools.ca"
  rules:
  - backendRefs:
    - name: superset
      port: 8088
