# genk8s:hash=989270315a607e3ad7929c4885b7bb27
global:
  domain: argocd.gpotools.ca

configs:
  params:
    server.insecure: true
  cm:
    accounts.rsalmond: "apiKey, login"

server:
  httproute:
    enabled: true
    hostnames: ["argocd.gpotools.ca"]
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gpotools
      namespace: gateway
      sectionName: tls

dex:
  enabled: false
