apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: superset
  namespace: gateway
spec:
  issuerRef:
    name: letsencrypt-prod
  secretName: superset
  dnsNames:
  - superset.gpotoolsstage.ca

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grassroots
  namespace: gateway
spec:
  issuerRef:
    name: letsencrypt-prod
  secretName: grassroots
  dnsNames:
  - grassroots.gpotoolsstage.ca

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: gateway
spec:
  issuerRef:
    name: letsencrypt-prod
  secretName: argocd
  dnsNames:
  - argocd.gpotoolsstage.ca
