apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gpotools
spec:
  # this gatewayClass is the incantation for the current gen ALB (not classic)
  # https://docs.cloud.google.com/load-balancing/docs/https#load-balancer-mode
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      - kind: HTTPRoute
  - name: https
    hostname: superset.gpotoolsstage.ca
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: gpotools
    # only allow httproutes in the superset namespace to use this listener
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: superset
      kinds:
      - kind: HTTPRoute
  addresses:
  - type: NamedAddress
    value: gke-ingress-ip
