# genk8s:hash=0231ce43b6d29be2a10c2a2a78cc3905
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gpotools
  namespace: gateway
spec:
  # this gatewayClass is the incantation for the current gen ALB (not classic)
  # https://docs.cloud.google.com/load-balancing/docs/https#load-balancer-mode
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "*.gpotoolsstage.ca"
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      - kind: HTTPRoute
  - name: tls
    hostname: "*.gpotoolsstage.ca"
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard-gpotools
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      - kind: HTTPRoute
  addresses:
  - type: NamedAddress
    value: gke-ingress-ip
