# genk8s:hash=2ada9fdbffed2a148b3f7da910f4d149
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-gpotools
  namespace: gateway
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-prod
  secretName: wildcard-gpotools
  dnsNames:
  - "*.gpotoolsstage.ca"
