postgresql:
  image:
    # Use default registry and tag from PostgreSQL subchart,
    # but set repository to legacy images repository.
    repository: bitnamilegacy/postgresql
redis:
  image:
    # Same idea for Redis.
    repository: bitnamilegacy/redis
# Custom Superset image which contains their upstream release plus pip packages
# for MySQL and PostgreSQL drivers.
image:
  repository: northamerica-northeast2-docker.pkg.dev/gpo-eng-stage/gpo/apache-superset
  tag: 5.0.0