# genk8s:hash=7fc2b2c86613cfc089505443786c18fc
# +argocd:skip-file-rendering
global:
  domain: argocd.gpotoolsstage.ca

configs:
  params:
    server.insecure: true
  cm:
    accounts.rsalmond: "apiKey, login"

server:
  httproute:
    enabled: true
    hostnames: ["argocd.gpotoolsstage.ca"]
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gpotools
      namespace: gateway
      sectionName: tls

dex:
  enabled: false
