kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: superset
  labels:
    gateway: gpotools
spec:
  # this connects us to the gateway
  parentRefs:
  - kind: Gateway
    name: gpotools
    namespace: gateway
    sectionName: https
  hostnames:
  - "superset.gpotoolsstage.ca"
  rules:
  - backendRefs:
    - name: superset
      port: 8088
