# genk8s:hash=837d98298c53d1c3a1098f58e1d7e287
# +argocd:skip-file-rendering
postgresql:
  image:
    # Use default registry and tag from PostgreSQL subchart,
    # but set repository to legacy images repository.
    repository: bitnamilegacy/postgresql
redis:
  image:
    # Same idea for Redis.
    repository: bitnamilegacy/redis
# Custom Superset image which contains their upstream release plus pip packages
# for MySQL and PostgreSQL drivers.
image:
  repository: northamerica-northeast2-docker.pkg.dev/gpo-eng-stage/gpo/apache-superset
  tag: v0.0.1
# Enabling feature flags. Note this is Python code injected into config.py.
# See https://github.com/apache/superset/blob/master/RESOURCES/FEATURE_FLAGS.md
# and https://github.com/apache/superset/tree/master/helm/superset#values for
# details.
configOverrides:
  superset_config.py: |
    FEATURE_FLAGS = {
      DASHBOARD_RBAC: True,
    }
