apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gpotools
  namespace: gateway
spec:
  issuerRef:
    name: letsencrypt-prod
  secretName: gpotools
  dnsNames:
  - superset.gpotools.ca
