# genk8s:hash=a83ad77e8da8e71760d221576cc6947a
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-gpotools
  namespace: gateway
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-prod
  secretName: wildcard-gpotools
  dnsNames:
  - "*.gpotools.ca"
