apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-config
  namespace: superset
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    # create a secret called "superset-config"
    name: superset-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      # populated with data from a GCP SM secret called "superset-config"
      key: superset-config

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-env
  namespace: superset
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    name: superset-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: superset-env

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-postgres-db
  namespace: superset
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    name: superset-postgres-db
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: superset-postgres-db
