apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: superset
  namespace: superset
spec:
  default:
    config:
      httpHealthCheck:
        port: 8088
        requestPath: /health
      type: HTTP
  targetRef:
    group: ""
    kind: Service
    name: superset
