# NOTE: stage here means LetsEncrypt's stage service, nothing
# to do with OUR environment.

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-stage
  namespace: gateway
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ianedington@gpo.ca
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-stage
    # Enable the HTTP-01 challenge provider using Gateway API
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: gpotools
            namespace: gateway
            kind: Gateway
            sectionName: http
