# this file is generated dynamically, hand edits will be overwritten
apiVersion: v1
data:
  GOOGLE_AUTH_CALLBACK_URL: "https://grassroots.gpotoolsstage.ca/api/auth/google/callback"
  GOOGLE_CLIENT_ID: "gpo-grassroots-stage"
  VITE_BACKEND_HOST: "https://grassroots.gpotoolsstage.ca/api"
  VITE_FRONTEND_HOST: "https://grassroots.gpotoolsstage.ca"
kind: ConfigMap
metadata:
  name: grassroots
