# this file is generated dynamically, hand edits will be overwritten
apiVersion: v1
data:
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:bBclQTHL2xAQRTKbTuA3kDCQwBoyJvAj4iQm8V9n+2Z8hm+Rji+CMVYlKlLTHK4QdkgsFccr7hmIdfDPvOy+G3Lyrgrdnv1x6mS1oT/SYXWwfzB6y9Ru6i4aFBOfynU0,iv:IWyKgX5jTDBpcTU/4YWiQU+N6Qppz3P/CKNyg3pbqQo=,tag:eoYLhrOKuwbq/c0uafymHg==,type:str]
kind: Secret
metadata:
    name: grassroots
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ca-central-1:542371827759:key/bb9f8f84-d188-42d8-8634-f2b0b2941228
          created_at: "2025-11-27T20:31:07Z"
          enc: AQICAHhZypHYCMOtYmz4bDXC0xKy6e0KEybm1OnmjaTzxiidDwHFTdsqRjQpe+6Xj94Pe96RAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTrgbOEE6X6SacLEiAgEQgDvnL9e1fsqOSJI/t+3Wl2HcIKwZMelaNqdyfF9p5hvYoLi7A5gVKERpBT518JcSKKFPu/Wdshe2BhEijg==
          aws_profile: gpo-stage
    lastmodified: "2025-11-27T20:31:07Z"
    mac: ENC[AES256_GCM,data:3i+oSaT4VeF6wQGaiQXxbyNbMNmA5HKHCm57onB/ZHXpRTkDziit34T9VYdPFv0aKk7a8CM4PKaiuTbqWbVgxNSkPHfyNxEJLD6jOlUubAgmSNh3DFytJ4Rq8VoUPm6cfJ+ch3jWuA3dEtuJdp2r2inNSFqETUoYcIkslh26q1c=,iv:r1nso41nTTudKEA6u1XupSJdduA7Y8tnrxLoouuXDQ8=,tag:aZQitB1athFnLw8MfeqNRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
